language: php
php:
  - 5.4

env:
  - DB=mysql

before_install:
  - sudo apt-get install rdiff-backup
  - sudo rdiff-backup --exclude /tmp --exclude /mnt --exclude /proc --exclude /sys --exclude /dev / /tmp/backup
  - sudo rm -rf /etc/apt/sources.list.d/*
  - sudo add-apt-repository --yes ppa:chris-lea/node.js
  - sudo apt-get update > /dev/null

install:
  - cat bin/provision.sh | sudo sh
  - cd ~
  - mkdir -p ~/.ssh
  - echo "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - git clone git@github.com:rarescosma/skype-notify.git dest
  - cp /tmp/diff.tar.gz dest
  - cd dest
  - git add .
  - git commit -m "up"
  - git push

script:
  - ./bin/test.sh

notifications:
  email: false
